FILE_METADATA = False
MULTITHREADED = True

MAX_LENGTH = 32767
MAX_SEQUENCE = 65535
MAX_PACKET_LENGTH = 1+2+2+2+32767

TYPE_DATA = 0
TYPE_ACK = 1
TYPE_FIN = 2
TYPE_FINACK = 3
TYPE_MDATA = 4
TYPE_MACK = 5

AVAILABLE_TYPES = [TYPE_DATA, TYPE_ACK, TYPE_FIN, TYPE_FINACK, TYPE_MDATA, TYPE_MACK] if FILE_METADATA else [TYPE_DATA, TYPE_ACK, TYPE_FIN, TYPE_FINACK]

MAX_SENDER_THREADS = 5 if MULTITHREADED else 1
RESEND_TIMER = 2
RESEND_TIMER_TICK = 2

CHUNK_SIZE = 32767